package cli

// commands is the whole command table. Each stage-1a task adds its line here.
var commands = map[string]command{
	"approve":    approveCommand,
	"area":       areaCommand,
	"brain":      brainCommand,
	"case":       caseCommand,
	"cases":      casesCommand,
	"check":      checkCommand,
	"config":     configCommand,
	"convert":    convertCommand,
	"dev":        devCommand,
	"doctor":     statusCommand,
	"embed":      embedCommand,
	"explain":    statusCommand,
	"fetch":      fetchCommand,
	"flow":       flowCommand,
	"graph":      graphCommand,
	"hook":       hookCommand,
	"init":       initCommand,
	"lint":       lintCommand,
	"mcp":        mcpCommand,
	"merge-hook": mergeHookCommand,
	"reconcile":  reconcileCommand,
	"reindex":    reindexCommand,
	"upgrade":    upgradeCommand,
	"serve":      serveCommand,
	"status":     statusCommand,
	"wiki":       wikiCommand,
	"wiki-gate":  wikiGateCommand,
	"worktree":   worktreeCommand,
}
